### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by develcooking** [wbernard/Memorado#71]
Hi there, very nice projects works and look very nice. So I wounded if it would be possible to make a port to android. If this isn't in the scope of this project i would create a database complaint fork

**Comment by bertob** [comment]
I don't think there's currently an easy way to ship GTK apps on Android. There are some efforts in that direction, but I wouldn't expect it to become possible in the next year or so realistically. If you're interested in a compatible Android app a separate native Android code base is probably the way to go.
